name: Deploy

env:
  VITE_FIREBASE_API_KEY: <API key>
  VITE_FIREBASE_AUTH_DOMAIN: <app name>.firebaseapp.com
  VITE_FIREBASE_PROJECT_ID: <app name>
  VITE_FIREBASE_STORAGE_BUCKET: <app name>.appspot.com
  VITE_FIREBASE_MESSAGING_SENDER_ID: <sender id>
  VITE_FIREBASE_APP_ID: <app id>
  VITE_FIREBASE_VAPID_KEY: <VAPID key>
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build -- --base=/rockstar-pwa-fcm

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
